import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const basePath = (process.env.BASE_PATH || '').replace(/\/+$/, '');
if (basePath && !/^\/[A-Za-z0-9._-]+$/.test(basePath)) throw new Error('BASE_PATH must be empty or a repository path like /portfolio.');
const profile = JSON.parse(fs.readFileSync(path.join(root, 'content/profile.json'), 'utf8'));
const esc = (s = '') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readContent(file) {
  const raw = fs.readFileSync(file, 'utf8');
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  const meta = {};
  if (match) for (const line of match[1].split(/\r?\n/)) {
    const index = line.indexOf(':');
    if (index > -1) meta[line.slice(0,index).trim()] = line.slice(index+1).trim();
  }
  return { ...meta, body: match ? match[2].trim() : raw.trim(), slug: path.basename(file, '.md') };
}
const projects = fs.readdirSync(path.join(root,'content/projects')).filter(f=>f.endsWith('.md')).map(f=>readContent(path.join(root,'content/projects',f)));
projects.sort((a,b)=>['temporal','multimodal','engineering'].indexOf(a.cover)-['temporal','multimodal','engineering'].indexOf(b.cover));
const routes = [['/','首页'],['/research/','研究'],['/projects/','项目与演示'],['/experience/','经历'],['/cv/','简历'],['/writing/','写作']];
const playIcon = '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 5v14l11-7z"/></svg>';
const pauseIcon = '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6 5h4v14H6zm8 0h4v14h-4z"/></svg>';
function diagram(type) {
  if(type==='temporal') return `<svg viewBox="0 0 560 250" role="img" aria-label="视频帧与时序关系示意"><defs><pattern id="grid-t" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="currentColor" opacity=".09"/></pattern></defs><rect width="560" height="250" fill="url(#grid-t)"/><path d="M52 169H508" stroke="currentColor" opacity=".3"/><path d="M61 134C97 134 112 137 141 122S189 49 227 73 275 145 316 112 373 48 409 67 458 139 497 100" fill="none" stroke="currentColor" stroke-width="3"/><g fill="currentColor">${[70,140,210,280,350,420,490].map((x,i)=>`<rect x="${x-17}" y="182" width="34" height="24" rx="3" opacity="${.2+i*.1}"/><circle cx="${x}" cy="169" r="3"/>`).join('')}</g><text x="52" y="37" fill="currentColor" font-size="12" font-family="monospace" letter-spacing="2">TEMPORAL CONTEXT</text></svg>`;
  if(type==='multimodal') return `<svg viewBox="0 0 560 250" role="img" aria-label="视觉与语言交互示意"><g stroke="currentColor" opacity=".22">${[0,1,2,3].flatMap(i=>[0,1,2].map(j=>`<path d="M${100+i*116} 72L${160+j*116} 176"/>`)).join('')}</g><g fill="currentColor">${[0,1,2,3].map(i=>`<rect x="${80+i*116}" y="52" width="40" height="40" rx="8" opacity="${.35+i*.15}"/>`).join('')}${[0,1,2].map(i=>`<circle cx="${160+i*116}" cy="176" r="16" opacity="${.45+i*.2}"/>`).join('')}</g><text x="35" y="37" fill="currentColor" font-size="12" font-family="monospace" letter-spacing="2">CROSS-MODAL ALIGNMENT</text><text x="35" y="226" fill="currentColor" font-size="12" font-family="monospace">vision · language · time</text></svg>`;
  return `<svg viewBox="0 0 560 250" role="img" aria-label="视频推理流程示意"><g fill="none" stroke="currentColor"><rect x="44" y="80" width="112" height="82" rx="8" opacity=".6"/><rect x="224" y="80" width="112" height="82" rx="8" opacity=".6"/><rect x="404" y="80" width="112" height="82" rx="8" opacity=".6"/><path d="M156 121H224M336 121H404" opacity=".4"/></g><g fill="currentColor" font-size="13" font-family="monospace" text-anchor="middle"><text x="100" y="126">INPUT</text><text x="280" y="126">MODEL</text><text x="460" y="126">OUTPUT</text></g><g fill="currentColor">${[0,1,2,3,4].map(i=>`<rect x="${247+i*13}" y="98" width="6" height="7" opacity=".5"/>`).join('')}</g><text x="44" y="37" fill="currentColor" font-size="12" font-family="monospace" letter-spacing="2">REPRODUCIBLE PIPELINE</text></svg>`;
}
function projectCard(p, i) {
  return `<a class="project-card" href="/projects/${esc(p.slug)}/" data-category="${esc(p.category)}"><div class="project-art art-${esc(p.cover)}">${diagram(p.cover)}<span class="art-index">0${i+1}</span></div><div class="project-copy"><div class="card-meta"><span>${p.category==='research'?'RESEARCH':'ENGINEERING'}</span><span class="draft-tag">${esc(p.status)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.subtitle)}</p><div class="tag-row">${p.tags.split(',').map(t=>`<span>${esc(t)}</span>`).join('')}</div></div></a>`;
}
function shell(title, active, body, extra='') {
  const nav = routes.map(([url,label])=>`<a href="${url}" ${active===url?'aria-current="page"':''}>${label}</a>`).join('');
  const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${esc(profile.role)}方向的个人科研主页、项目演示与简历。"><meta name="theme-color" content="#122821"><meta property="og:title" content="${esc(title)} · ${esc(profile.name)}"><meta property="og:description" content="研究、视频项目与实践记录。"><title>${esc(title)} · ${esc(profile.name)}</title><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='10' fill='%23122821'/%3E%3Cpath d='M10 11v18l22-9z' fill='%23c8f36b'/%3E%3C/svg%3E"><link rel="stylesheet" href="/assets/styles.css"><script defer src="/assets/site.js"></script></head><body><a class="skip-link" href="#main">跳到正文</a><header class="site-header"><div class="header-inner"><a class="brand" href="/" aria-label="个人网站首页"><span class="brand-mark">v<span>.</span></span><span class="brand-name">${esc(profile.name)}<small>VIDEO UNDERSTANDING</small></span></a><button class="menu-toggle" type="button" aria-label="打开导航" aria-expanded="false" aria-controls="main-nav"><span></span><span></span></button><nav id="main-nav" aria-label="主导航">${nav}</nav><a class="header-cv" href="/cv/">查看简历</a></div></header><main id="main">${body}</main><footer class="site-footer"><div class="footer-top"><div><p class="eyebrow light">RESEARCH / BUILD / SHARE</p><h2>Keep looking.<br><em>Keep understanding.</em></h2></div><div class="footer-contact"><span>交流与合作</span>${profile.email?`<a class="email-link" href="mailto:${esc(profile.email)}">${esc(profile.email)}</a>`:'<p class="email-link muted-light">邮箱待补充</p>'}<p>科研合作 · 项目交流 · 实习机会</p></div></div><div class="footer-bottom"><span>© 2026 ${esc(profile.name)}</span><span>${profile.isDraft?'个人网站初稿 · 资料待完善':'AI · VIDEO UNDERSTANDING'}</span><a href="/cv/">CV / Résumé</a></div></footer>${extra}</body></html>`;
  return basePath ? html.replace(/\b(href|src|poster|data-academic|data-industry)="\/(?!\/)/g, `$1="${basePath}/`) : html;
}
function videoPlayer(compact=false, customVideo="", customPoster="") {
  return `<div class="video-console ${compact?'compact':''}" data-video-console><div class="console-head"><span class="console-label"><i></i> TEMPORAL VIEW</span><span>片段预览示意</span></div><div class="video-stage"><video muted playsinline preload="metadata" poster="${esc(customPoster || profile.demoPoster || "")}" aria-label="${customVideo || !profile.demoIsExample ? "视频演示片段" : "CC0 花朵与蜜蜂示例视频"}"><source src="${esc(customVideo || profile.demoVideo || "/assets/sample-video.mp4")}" type="video/mp4">你的浏览器不支持视频播放。</video><div class="video-cross top-left"></div><div class="video-cross bottom-right"></div><span class="frame-label">FRAME <b data-frame>000</b></span><span class="video-time" data-time>00:00.0</span><button class="video-play" type="button" aria-label="播放示例视频">${playIcon}</button></div><div class="console-timeline"><div class="timeline-label"><span>TIME / SEQUENCE</span><span data-duration>00:00</span></div><input class="video-scrub" type="range" min="0" max="100" value="0" step=".1" aria-label="视频时间轴"><div class="timeline-ticks"><span>START</span><span>CONTEXT</span><span>END</span></div></div><p class="video-note">${customVideo || !profile.demoIsExample ? "视频演示 · 可播放与拖动时间轴" : '交互示意，非个人研究成果 · <a href="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" target="_blank" rel="noopener noreferrer">MDN CC0 素材</a>'}</p></div>`;
}
function home() {
 return shell('首页','/',`<section class="hero page-width"><div class="hero-copy"><p class="eyebrow"><span class="tiny-line"></span> AI RESEARCH PORTFOLIO</p><h1>Beyond<br>the <em>frames.</em><span class="hero-dot"></span></h1><p class="hero-chinese">理解视频，不止于帧。</p><p class="hero-description">${esc(profile.intro)}</p><div class="hero-actions"><a class="button button-dark" href="/projects/">探索项目与演示</a><a class="text-link" href="/research/">了解我的研究</a></div><div class="hero-detail"><span>${esc(profile.role)}</span><span>${esc(profile.affiliation)}</span></div></div><div class="hero-visual">${videoPlayer(true)}<div class="visual-caption"><span>01 / VISION IN TIME</span><span>从画面，到上下文。</span></div></div></section><section class="focus-strip"><div class="page-width focus-inner"><span>研究与实践</span><strong>Video understanding</strong><span class="strip-divider"></span><strong>Temporal context</strong><span class="strip-divider"></span><strong>From ideas to implementation</strong></div></section><section class="section page-width"><div class="section-heading"><div><p class="eyebrow">SELECTED WORK / 01</p><h2>从问题出发，<br><span class="muted">让结果可见。</span></h2></div><div class="section-heading-side"><p>研究贡献与实现过程，都值得被看见。<br>下方为待替换的项目内容模板。</p><a class="text-link" href="/projects/">查看所有项目</a></div></div><div class="project-grid">${projects.slice(0,3).map(projectCard).join('')}</div></section><section class="about-section"><div class="page-width about-grid"><div><p class="eyebrow">ABOUT THE WORK / 02</p><h2>研究的深度。<br>实现的细节。</h2></div><div><p class="large-body">我的专业是人工智能，研究方向为视频理解。这个网站将把研究问题、实验过程与实际实现连接起来。</p><p class="muted body-copy">每个项目分别呈现方法与证据、个人贡献，以及可复现的实现。科研经历与实习经历也将持续更新。</p><div class="about-links"><a href="/research/">研究与论文</a><a href="/experience/">科研与实习经历</a><a href="/cv/">学术 CV / 求职简历</a></div></div></div></section><section class="section page-width writing-preview"><div class="section-heading"><div><p class="eyebrow">NOTES & IDEAS / 03</p><h2>留下思考的过程。</h2></div><a class="text-link" href="/writing/">阅读写作</a></div>${articles.slice(0,1).map(a=>`<a class="writing-row" href="/writing/${esc(a.slug)}/"><span class="writing-index">01</span><div><span class="eyebrow">${esc(a.status)} · ${esc(a.category)}</span><h3>${esc(a.title)}</h3></div><span class="writing-type">阅读</span></a>`).join('')}</section>`);
}
function save(route, html) {
 const dir=path.join(out,route.replace(/^\//,'')); fs.mkdirSync(dir,{recursive:true}); fs.writeFileSync(path.join(dir,'index.html'),html);
}
function md(text) {
  let list = false;
  const result = [];
  const inline = s=>esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`(.+?)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|\/[\w/.-]+)\)/g,'<a href="$2">$1</a>');
  for (const line of text.split(/\r?\n/)) {
    if(!line.trim()){if(list){result.push('</ul>');list=false;}continue;}
    if(line.startsWith('- ')){if(!list){result.push('<ul>');list=true;}result.push(`<li>${inline(line.slice(2))}</li>`);continue;}
    if(list){result.push('</ul>');list=false;}
    const heading=line.match(/^(#{1,3})\s+(.+)/);
    if(heading)result.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`);
    else result.push(`<p>${inline(line)}</p>`);
  }
  if(list)result.push('</ul>');return result.join('\n');
}
const publications=JSON.parse(fs.readFileSync(path.join(root,'content/publications.json'),'utf8'));
const experience=JSON.parse(fs.readFileSync(path.join(root,'content/experience.json'),'utf8'));
const cv=JSON.parse(fs.readFileSync(path.join(root,'content/cv.json'),'utf8'));
const articles=fs.readdirSync(path.join(root,'content/articles')).filter(f=>f.endsWith('.md')).map(f=>readContent(path.join(root,'content/articles',f))).sort((a,b)=>b.date.localeCompare(a.date));
function pageHeading(label,title,description='') {return `<div class="page-heading page-width"><p class="eyebrow">${label}</p><h1>${title}</h1>${description?`<p class="page-description">${description}</p>`:''}</div>`;}
function empty(icon,title,text,link='') {return `<div class="empty-state"><span class="empty-symbol" aria-hidden="true">${icon}</span><div><h3>${title}</h3><p>${text}</p>${link}</div></div>`;}
function publicationList() {
 if(!publications.length)return empty('P','公开成果待补充','这里将展示论文、预印本与相关研究成果。每项成果可关联论文、代码和项目演示。');
 return publications.map((p,i)=>`<article class="publication"><span class="publication-number">${String(i+1).padStart(2,'0')}</span><div><p class="eyebrow">${esc(p.venue||p.status||'研究成果')} · ${esc(p.year||'')}</p><h3>${esc(p.title)}</h3><p class="publication-authors">${esc(p.authors)}</p><div class="publication-links">${[['论文',p.url],['PDF',p.pdf],['代码',p.code],['项目',p.project]].filter(x=>x[1]).map(([label,url])=>`<a class="text-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}</a>`).join('')}${p.bibtex?`<button type="button" class="text-link copy-citation" data-citation="${esc(p.bibtex)}">复制 BibTeX</button>`:''}</div></div></article>`).join('');
}
function researchPage(){return shell('研究','/research/',pageHeading('RESEARCH / QUESTIONS & EVIDENCE','从问题，到证据。','视频理解领域的研究、方法与成果。')+`<section class="page-width research-overview"><div class="prose">${md(fs.readFileSync(path.join(root,'content/research.md'),'utf8'))}</div><aside class="research-aside"><p class="eyebrow">RESEARCH FOCUS</p><h2>Video<br><em>Understanding.</em></h2><div class="aside-line"></div><p>人工智能 · 视频理解</p><span class="draft-tag">具体研究课题待补充</span><a class="button button-outline" href="/projects/">查看项目与演示</a></aside></section><section class="section page-width"><div class="section-heading"><div><p class="eyebrow">PUBLICATIONS & PREPRINTS</p><h2>论文与成果</h2></div>${profile.scholar?`<a class="text-link" href="${esc(profile.scholar)}" target="_blank" rel="noopener noreferrer">Google Scholar</a>`:'<span class="subtle-label">发表状态将如实标注</span>'}</div>${publicationList()}</section><section class="research-bottom page-width"><p>研究材料与项目实现相互关联。</p><a href="/projects/">项目与演示</a><a href="/cv/">完整学术 CV</a></section>`);}
function projectsPage(){return shell('项目与演示','/projects/',pageHeading('PROJECTS / RESEARCH IN PRACTICE','让工作，<em>被看见。</em>','研究问题、方法设计、个人贡献，以及可观察的实现效果。')+`<section class="page-width projects-section"><div class="filter-bar" role="group" aria-label="项目分类"><button class="filter-button active" type="button" data-filter="all" aria-pressed="true">全部项目 <span>${projects.length}</span></button><button class="filter-button" type="button" data-filter="research" aria-pressed="false">研究项目</button><button class="filter-button" type="button" data-filter="engineering" aria-pressed="false">工程实践</button><p>当前展示内容模板，待替换为真实项目</p></div><div class="project-grid" data-project-grid>${projects.map(projectCard).join('')}</div><p class="filter-empty" hidden>此分类下暂无项目。</p></section><section class="demo-section"><div class="page-width demo-grid"><div><p class="eyebrow">VIDEO / TEMPORAL PREVIEW</p><h2>时间轴上的<br>每一刻。</h2><p class="body-copy muted">播放、暂停与拖动时间轴，浏览视频中的不同片段。这里先用开放素材演示交互，之后可替换为你的模型预测和实验案例。</p><div class="demo-legend"><span>可播放视频</span><span>可拖动时间轴</span><span>个人结果待上传</span></div></div>${videoPlayer()}</div></section>`);}
function projectPage(p){return shell(p.title,'/projects/',`<div class="page-width breadcrumb"><a href="/projects/">项目与演示</a><span>/</span><span>${esc(p.title)}</span></div><div class="project-detail-heading page-width"><div><p class="eyebrow">${p.category==='research'?'RESEARCH PROJECT':'ENGINEERING PROJECT'} · ${esc(p.status)}</p><h1>${esc(p.title)}</h1><p>${esc(p.subtitle)}</p><div class="tag-row">${p.tags.split(',').map(t=>`<span>${esc(t)}</span>`).join('')}</div></div><div class="detail-art art-${esc(p.cover)}">${diagram(p.cover)}</div></div><section class="page-width detail-layout"><aside class="detail-sidebar"><p class="eyebrow">PROJECT INFORMATION</p><dl><dt>项目状态</dt><dd>${esc(p.status || "待补充")}</dd><dt>时间</dt><dd>${esc(p.period || "待补充")}</dd><dt>我的角色</dt><dd>${esc(p.role || "待补充")}</dd><dt>相关材料</dt><dd>${p.code ? `<a class="text-link" href="${esc(p.code)}" target="_blank" rel="noopener noreferrer">代码仓库</a>` : "代码链接待补充"}${p.paper ? `<br><a class="text-link" href="${esc(p.paper)}" target="_blank" rel="noopener noreferrer">论文链接</a>` : ""}</dd></dl><a class="text-link" href="/projects/">返回项目列表</a></aside><article class="prose project-prose">${md(p.body)}<div class="project-next"><h3>视频与案例</h3>${p.video ? videoPlayer(false,p.video,p.poster) : "<p>该项目的真实演示视频、预测结果和失败案例待上传。</p>"}</div></article></section>`);}
function entries(items,type){
 if(!items.length)return empty(type==='education'?'E':type==='research'?'R':type==='industry'?'I':'A',({education:'教育背景待补充',research:'科研经历待补充',industry:'实习与工作经历待补充',awards:'奖项与学术服务待补充'})[type],'尚未填写个人经历，页面没有添加虚构机构、任职或成果。');
 return items.map(e=>`<article class="experience-entry"><div class="experience-date">${esc(e.period||'')}</div><div><h3>${esc(e.title||e.degree||'')}</h3><p class="entry-organization">${esc(e.organization||'')}</p>${e.description?`<p>${esc(e.description)}</p>`:''}${e.highlights?.length?`<ul>${e.highlights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</div></article>`).join('');
}
function experiencePage(){return shell('经历','/experience/',pageHeading('EXPERIENCE / THE PATH SO FAR','持续学习，<br><span class="muted">持续实践。</span>','教育背景、科研经历与工程实践。')+`<div class="page-width experience-layout"><aside class="section-nav"><p class="eyebrow">CONTENTS</p><a href="#education">教育背景</a><a href="#research-experience">科研经历</a><a href="#industry">实习与工作</a><a href="#awards">奖项与服务</a></aside><div class="experience-content"><section id="education"><div class="experience-title"><span>01</span><h2>教育背景</h2></div>${entries(experience.education,'education')}</section><section id="research-experience"><div class="experience-title"><span>02</span><h2>科研经历</h2></div>${entries(experience.research,'research')}</section><section id="industry"><div class="experience-title"><span>03</span><h2>实习与工作</h2></div>${entries(experience.industry,'industry')}</section><section id="awards"><div class="experience-title"><span>04</span><h2>奖项与服务</h2></div>${entries(experience.awards,'awards')}</section></div></div>`);}
function cvSection(title,body){return `<section class="cv-section"><h3>${title}</h3><div>${body}</div></section>`;}
function cvEntries(items){return items.length?items.map(e=>`<div class="cv-entry"><strong>${esc(e.title||e.degree||'')}</strong><span>${esc(e.period||'')}</span><p>${esc(e.organization||'')}</p>${e.description?`<p>${esc(e.description)}</p>`:''}${e.highlights?.length?`<ul>${e.highlights.map(h=>`<li>${esc(h)}</li>`).join('')}</ul>`:''}</div>`).join(''):'<p class="cv-placeholder">待补充</p>';}
function cvDoc(academic){return `<div class="cv-paper" id="${academic?'academic':'industry'}-panel" role="tabpanel" aria-labelledby="${academic?'academic':'industry'}-tab" ${academic?'':'hidden'}><header class="cv-paper-header"><div><p class="cv-kicker">${academic?'CURRICULUM VITAE':'RÉSUMÉ'}</p><h2>${esc(profile.name)}${profile.englishName?`<small>${esc(profile.englishName)}</small>`:''}</h2><p>${esc(profile.role)}</p></div><div class="cv-contact"><span>${esc(profile.affiliation)}</span>${profile.email?`<a href="mailto:${esc(profile.email)}">${esc(profile.email)}</a>`:'<span>邮箱待补充</span>'}${profile.github?`<a href="${esc(profile.github)}">GitHub</a>`:''}</div></header>${profile.isDraft?'<p class="cv-draft-note">个人资料待填写 · 此文档为简历结构初稿</p>':''}${cvSection(academic?'研究兴趣':'个人简介',`<p>${esc(academic?cv.academicInterests.join(' · '):cv.summary)}</p>`)}${cvSection('教育背景',cvEntries(experience.education))}${academic?cvSection('科研经历',cvEntries(experience.research)):cvSection('实习与工作经历',cvEntries(experience.industry))}${cvSection(academic?'论文与成果':'代表项目',academic?(publications.length?publications.map(p=>`<p><strong>${esc(p.title)}</strong><br>${esc(p.authors)}. ${esc(p.venue)}, ${esc(p.year)}.</p>`).join(''):'<p class="cv-placeholder">尚未填写公开成果</p>'):(cv.selectedProjects.length?cvEntries(cv.selectedProjects):'<p class="cv-placeholder">真实项目与量化成果待补充</p>'))}${cvSection(academic?'实习与实践':'技能与工具',academic?cvEntries(experience.industry):(cv.skills.length?`<p>${esc(cv.skills.join(' · '))}</p>`:'<p class="cv-placeholder">技能与熟练程度待补充</p>'))}${cvSection('奖项与服务',cvEntries(experience.awards))}<div class="cv-paper-foot"><span>${esc(profile.name)} · ${academic?'Academic CV':'Industry Résumé'}</span><span>更新 ${esc(profile.updated)}</span></div></div>`;}
function cvPage(){return shell('简历','/cv/',pageHeading('CV / TWO PERSPECTIVES','同一段经历，<br><span class="muted">清晰的不同侧重。</span>','学术 CV 侧重研究积累；求职简历突出个人贡献与实现效果。')+`<section class="page-width cv-layout"><div class="cv-toolbar"><div class="cv-tabs" role="tablist" aria-label="简历版本"><button type="button" role="tab" id="academic-tab" aria-controls="academic-panel" aria-selected="true" data-cv-tab="academic">学术 CV</button><button type="button" role="tab" id="industry-tab" aria-controls="industry-panel" aria-selected="false" tabindex="-1" data-cv-tab="industry">求职简历</button></div><div class="cv-actions">${cv.academicPdf||cv.industryPdf?`<a class="button button-outline" data-cv-download data-academic="${esc(cv.academicPdf)}" data-industry="${esc(cv.industryPdf)}" href="${esc(cv.academicPdf||cv.industryPdf)}" download>下载已有 PDF</a>`:''}<button class="button button-dark print-cv" type="button">打印 / 保存为 PDF</button></div></div>${cvDoc(true)}${cvDoc(false)}<p class="cv-hint">保存时选择浏览器的“另存为 PDF”。当前内容为待填写的简历初稿。</p></section>`);}
function writingPage(){return shell('写作','/writing/',pageHeading('WRITING / NOTES IN PROGRESS','把思考，<em>写下来。</em>','研究笔记、论文复现与工程记录。')+`<section class="page-width writing-list">${articles.map((a,i)=>`<a class="writing-list-item" href="/writing/${esc(a.slug)}/"><span class="writing-date">${esc(a.date.replaceAll('-','.'))}<small>${esc(a.status||'')}</small></span><div><p class="eyebrow">${esc(a.category)}</p><h2>${esc(a.title)}</h2><p>${esc(a.subtitle||'')}</p></div><span class="writing-read">阅读</span></a>`).join('')}</section>`);}
function articlePage(a){const headings=a.body.split(/\r?\n/).filter(x=>x.startsWith('## ')).map(x=>x.slice(3));let html=md(a.body);let count=0;html=html.replace(/<h2>/g,()=>`<h2 id="section-${++count}">`);return shell(a.title,'/writing/',`<div class="page-width breadcrumb"><a href="/writing/">写作</a><span>/</span><span>${esc(a.category)}</span></div><header class="article-header page-width"><p class="eyebrow">${esc(a.category)} · ${esc(a.status||'')}</p><h1>${esc(a.title)}</h1><p>${esc(a.subtitle||'')}</p><div class="article-meta"><span>${esc(a.date)}</span><span>${esc(profile.name)}</span><span>约 ${Math.max(1,Math.ceil(a.body.length/400))} 分钟阅读</span></div></header><div class="page-width article-layout"><aside class="article-toc"><p class="eyebrow">ON THIS PAGE</p>${headings.map((h,i)=>`<a href="#section-${i+1}">${esc(h)}</a>`).join('')}</aside><article class="prose article-body">${html}<div class="article-end"><span>END OF NOTE</span><a class="text-link" href="/writing/">返回全部写作</a></div></article></div>`);}
fs.mkdirSync(path.join(out,'assets'),{recursive:true});
for(const f of fs.readdirSync(path.join(root,'assets'))) fs.copyFileSync(path.join(root,'assets',f),path.join(out,'assets',f));
fs.writeFileSync(path.join(out, '.nojekyll'), '');
save('/',home());
save('/research/',researchPage());
save('/projects/',projectsPage());
for(const p of projects)save(`/projects/${p.slug}/`,projectPage(p));
save('/experience/',experiencePage());
save('/cv/',cvPage());
save('/writing/',writingPage());
for(const a of articles)save(`/writing/${a.slug}/`,articlePage(a));
fs.writeFileSync(path.join(out,'404.html'),shell('页面不存在','',pageHeading('404 / PAGE NOT FOUND','这页暂时不存在。','')+'<div class="page-width not-found"><a class="button button-dark" href="/">返回首页</a></div>'));
console.log(`Built ${7+projects.length+articles.length} pages. Content source: content/.`);
